### PR TITLE
Feature: More than 2 individual devices

### PR DESCRIPTION
**Pull request by MelchMwoan**
Good afternoon, i have been using this card for a couple of weeks now and i really missed the feature to show more than 2 individual devices inside the card. 
So I spent the last couple of nights to implement this feature myself and I am really glad with how it turned out.

When you only implement 2 individual devices, it will just show the card in the old way:
image

But when you configure 3 or more it will automatically add an extra column on the right with the extra individual devices:
image

Minor issues:
- Animations of the 3 extra devices are a bit jumpy when it goes back to the begin but because they are overlays i currently cant use overflow hidden. (dont mind the total home Wattage, that is due to using the same sensor for the indivs)
[chrome-capture-2024-0-5.webm](https://github.com/flixlix/power-flow-card-plus/assets/64213755/6158f6b4-f690-4e66-b620-38f8f6897112)
- This code might make the card even heavier than it currently is. I don't know for sure since I never had any issues with either the old or the new variant.

Related issues:
#443 #54

### CODE REVIEW

**Comment by matze19999** [comment]
Can you please provide the compiled .js file? i tried to compile it with npm, but had no success. :/

**Comment by MelchMwoan** [comment]
Sure thing, 
[power-flow-card-plus.zip](https://github.com/flixlix/power-flow-card-plus/files/13849322/power-flow-card-plus.zip)
Unzip that folder and the compiled file is in there, cant directly upload a .js file

**Comment by matze19999** [comment]
Thank you! 😊

**Comment by Kloana001** [comment]
Hello,
Is there a guide on how to install it?
The normal map is displayed.
Only the other entries are missing.
I'm a complete newbie when it comes to HA...
Thank you

**Comment by MelchMwoan** [comment]
The best way to install it is by using the manual install https://hacs.xyz/docs/faq/custom_repositories/ 
But instead of using the .js from the releases you need to use the .js that I sent earlier.

If you installed this card via HACS, you need to remove it from HACS. Otherwise the manual installed one will be overridden with the old one.

You probably need to refresh your cache after the installment.
Other than that the new card should just work.

The configuration of the extra individuals is as easy as using the same configurations you would use for [individual1 and individual2](https://github.com/flixlix/power-flow-card-plus?tab=readme-ov-file#entities-object), but now you can also use individual3, individual4 and individual5.

Hope this explains it :)

**Comment by Kloana001** [comment]
Thank you.
now it worked.
vielen dank.
jetzt hat es geklappt.

**Comment by fnxpt** [comment]
it would be nice to have this even if its not 100% dynamic.. ideally individual services should be an array

**Comment by MelchMwoan** [comment]
Closed since the new version of the card already supports multiple individuals

**Pull request closed without merging**
